/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.coffeymachine;

import com.sun.source.tree.Tree;
import java.util.ArrayList;
import javax.swing.JOptionPane;
 
/**
 *
 * @author 97056
 */
public class CoffeeFrame extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeFrame
     */
     CoffeeMachine cofemech=new CoffeeMachine(new WaterTank(0), 0);
     Grinder cof = null;
     ArrayList<Grinder> cups=new ArrayList<>();
     
     
    
    public CoffeeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Arabicca = new javax.swing.JRadioButton();
        Reposo = new javax.swing.JRadioButton();
        Mix = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        Amricano = new javax.swing.JRadioButton();
        Espresso = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Single = new javax.swing.JRadioButton();
        Double = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        SugarFeild = new javax.swing.JTextField();
        Start = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        roast10 = new javax.swing.JRadioButton();
        roast5 = new javax.swing.JRadioButton();
        Cheac = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        watertextbox = new javax.swing.JTextField();
        beanstextbox = new javax.swing.JTextField();
        trashbox = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tab1Area = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailarea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Machine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Engravers MT", 1, 24))); // NOI18N

        jButton1.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton1.setText("fill Water");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton4.setText("Clean trash");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        jButton5.setText("FILL Beans");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(89, 89, 89))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selection", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 18))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 0));

        buttonGroup1.add(Arabicca);
        Arabicca.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Arabicca.setSelected(true);
        Arabicca.setText("Arabica");
        Arabicca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArabiccaActionPerformed(evt);
            }
        });

        buttonGroup1.add(Reposo);
        Reposo.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Reposo.setText("Reposo");

        buttonGroup1.add(Mix);
        Mix.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Mix.setText("Mix 50% 50%");

        jLabel4.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        jLabel4.setText("Type of Coffee ");

        buttonGroup2.add(Amricano);
        Amricano.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Amricano.setSelected(true);
        Amricano.setText("Amricano");
        Amricano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmricanoActionPerformed(evt);
            }
        });

        buttonGroup2.add(Espresso);
        Espresso.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Espresso.setText("Espresso");

        jLabel7.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        jLabel7.setText("Beans type");

        jLabel8.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        jLabel8.setText("Type of Cup");

        buttonGroup3.add(Single);
        Single.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Single.setSelected(true);
        Single.setText("Single");
        Single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleActionPerformed(evt);
            }
        });

        buttonGroup3.add(Double);
        Double.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        Double.setText("Double");

        jLabel9.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        jLabel9.setText("Amount of Sugar ");

        Start.setFont(new java.awt.Font("Elephant", 1, 36)); // NOI18N
        Start.setText("Start");
        Start.setEnabled(false);
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        jLabel5.setText("Roast level");

        buttonGroup4.add(roast10);
        roast10.setFont(new java.awt.Font("Goudy Stout", 1, 10)); // NOI18N
        roast10.setText("10");

        buttonGroup4.add(roast5);
        roast5.setFont(new java.awt.Font("Goudy Stout", 1, 10)); // NOI18N
        roast5.setSelected(true);
        roast5.setText("5");

        Cheac.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        Cheac.setText("Check");
        Cheac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(221, 221, 221)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Arabicca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SugarFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Single)
                                    .addComponent(roast5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Amricano, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roast10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Espresso)
                                    .addComponent(Double)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Reposo)
                                        .addGap(58, 58, 58)
                                        .addComponent(Mix))))
                            .addComponent(Cheac, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arabicca)
                    .addComponent(Reposo)
                    .addComponent(Mix)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(roast10)
                    .addComponent(roast5))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Amricano)
                    .addComponent(Espresso))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Single)
                    .addComponent(Double))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(209, 209, 209))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SugarFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Cheac)
                        .addGap(18, 18, 18)
                        .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Container ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Expo M", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel1.setText("Beans");

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel2.setText("Water");

        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jLabel3.setText("Trash (Max 20)");

        watertextbox.setEditable(false);
        watertextbox.setFont(new java.awt.Font("Goudy Stout", 1, 8)); // NOI18N
        watertextbox.setText("0");
        watertextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watertextboxActionPerformed(evt);
            }
        });

        beanstextbox.setEditable(false);
        beanstextbox.setFont(new java.awt.Font("Goudy Stout", 1, 8)); // NOI18N
        beanstextbox.setText("0");
        beanstextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beanstextboxActionPerformed(evt);
            }
        });

        trashbox.setEditable(false);
        trashbox.setFont(new java.awt.Font("Goudy Stout", 1, 8)); // NOI18N
        trashbox.setText("0");
        trashbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trashboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(watertextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(963, 963, 963))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(beanstextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trashbox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beanstextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(watertextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trashbox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Tab1Area.setColumns(20);
        Tab1Area.setFont(new java.awt.Font("Engravers MT", 1, 24)); // NOI18N
        Tab1Area.setForeground(new java.awt.Color(0, 0, 0));
        Tab1Area.setRows(5);
        Tab1Area.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), " Machine Screan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 1, 18))); // NOI18N
        jScrollPane3.setViewportView(Tab1Area);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab1", jPanel3);

        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder("History"));
        jList1.setFont(new java.awt.Font("Headline R", 1, 10)); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        detailarea2.setEditable(false);
        detailarea2.setColumns(20);
        detailarea2.setFont(new java.awt.Font("Headline R", 1, 14)); // NOI18N
        detailarea2.setRows(5);
        detailarea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
        jScrollPane2.setViewportView(detailarea2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 391, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(0, 105, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("tab2", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        int index=jList1.getSelectedIndex();
        detailarea2.setText(cups.get(index).getInfo());
    }//GEN-LAST:event_jList1ValueChanged

    private void CheacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheacActionPerformed
        {
            if (SugarFeild.getText().equals("")||SugarFeild.getText().equals("0")) {

                JOptionPane.showMessageDialog(rootPane, "Please enter the Amount of Sugar");
                Cheac.setSelected(false);

            }
            else {
                Start.setEnabled(true);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CheacActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:

        int sugar=Integer.parseInt(SugarFeild.getText());
        int roastlevel;
        if(roast5.isSelected())
        roastlevel=5;
        if(roast10.isSelected());
        roastlevel=10;

        if(Arabicca.isSelected())
        {

            Beans beans=new Beans("Arabica", roastlevel);
            if(Amricano.isSelected())
            {

                if(Single.isSelected())
                {

                    cof=new Americano(sugar,beans);
                    cofemech.start(cof, cof.getType());

                }
                if(Double.isSelected())
                {

                    cof=new Americano(sugar, beans);
                    cofemech.start(cof, cof.getType());

                }
            }
            if(Espresso.isSelected())
            {
                if(Single.isSelected())
                {
                    cof= new Espresso(sugar, beans) {
                    };
                    cofemech.start(cof, cof.getType());

                }
                if(Double.isSelected())
                {
                    cof=new Espresso(sugar, beans) {
                    };
                    cofemech.start(cof, cof.getType());
                }
            }

        }
        if(Reposo.isSelected())
        {

            Beans beans=new Beans("Reposo", roastlevel);
            if(Amricano.isSelected())
            {
                if(Single.isSelected())
                {

                    cof=new Americano(sugar,beans);
                    cofemech.start(cof, cof.getType());

                }
                if(Double.isSelected())
                {

                    cof=new Americano(sugar, beans);
                    cofemech.start(cof, cof.getType());

                }
            }
            if(Espresso.isSelected())
            {
                if(Single.isSelected())
                {
                    cof= new Espresso(sugar, beans) {
                    };
                    cofemech.start(cof, cof.getType());

                }
                if(Double.isSelected())
                {
                    cof=new Espresso(sugar, beans) {
                    };
                    cofemech.start(cof, cof.getType());
                }
            }

        }
        if(Mix.isSelected())
        {

            Beans beans=new Beans("Mix", roastlevel);
            if(Amricano.isSelected())
            {
                if(Single.isSelected())
                {

                    cof=new Americano(sugar,beans);
                    cofemech.start(cof, cof.getType());

                }
                if(Double.isSelected())
                {

                    cof=new Americano(sugar, beans);
                    cofemech.start(cof, cof.getType());

                }
            }
            if(Espresso.isSelected())
            {
                if(Single.isSelected())
                {
                    cof= new Espresso(sugar, beans) {
                    };
                    cofemech.start(cof, cof.getType());

                }
                if(Double.isSelected())
                {
                    cof=new Espresso(sugar, beans) {
                    };
                    cofemech.start(cof, cof.getType());
                }
            }

        }
        if (cofemech.getWaterCapacity() < cof.getAmountOfWater()|| cofemech.getWaterCapacity()>1000) {
            Cheac.setSelected(false);
            return ;
        }

        if (cofemech.getBeanCapacity() < cof.getAmountOfBeans()|| cofemech.getBeanCapacity()>1000) {
            Cheac.setSelected(false);
            return;

        }

        if (cofemech.getCupsMade() >= 20) {
            Cheac.setSelected(false);
            return;
        }
        Grinder cof2;
        cof2=cof;
        cups.add(cof2);
        String[] s=new String[cups.size()];
        for (int i = 0; i < cups.size(); i++) {
            s[i]=cups.get(i).getType();

        }jList1.setListData(s);

        Tab1Area.setText(cofemech.getinfo(cof));
        Start.setEnabled(false);
        SugarFeild.setText("");
        Arabicca.setSelected(true);
        Amricano.setSelected(true);
        roast5.setSelected(true);
        Single.setSelected(true);
        Cheac.setSelected(false);
        beanstextbox.setText(String.valueOf(cofemech.getBeanCapacity()));
        watertextbox.setText(String.valueOf(cofemech.getWaterCapacity()));
        trashbox.setText(String.valueOf(cofemech.getCupsMade()));
    }//GEN-LAST:event_StartActionPerformed

    private void SingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleActionPerformed

    private void AmricanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmricanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmricanoActionPerformed

    private void ArabiccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArabiccaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArabiccaActionPerformed

    private void trashboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trashboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trashboxActionPerformed

    private void beanstextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beanstextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beanstextboxActionPerformed

    private void watertextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watertextboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_watertextboxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cofemech.refillbeans();
        beanstextbox.setText("1000");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cofemech.CupsTrash();
        trashbox.setText("0");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cofemech.refillwatertank();
        watertextbox.setText("1000");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Amricano;
    private javax.swing.JRadioButton Arabicca;
    private javax.swing.JCheckBox Cheac;
    private javax.swing.JRadioButton Double;
    private javax.swing.JRadioButton Espresso;
    private javax.swing.JRadioButton Mix;
    private javax.swing.JRadioButton Reposo;
    private javax.swing.JRadioButton Single;
    private javax.swing.JButton Start;
    private javax.swing.JTextField SugarFeild;
    private javax.swing.JTextArea Tab1Area;
    private javax.swing.JTextField beanstextbox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JTextArea detailarea2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JRadioButton roast10;
    private javax.swing.JRadioButton roast5;
    private javax.swing.JTextField trashbox;
    private javax.swing.JTextField watertextbox;
    // End of variables declaration//GEN-END:variables
}
